plugins {
	id 'org.springframework.boot'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter-kafka'
	implementation 'org.springframework.boot:spring-boot-starter-actuator'
	implementation 'com.fasterxml.jackson.core:jackson-databind'

	testImplementation 'org.springframework.boot:spring-boot-starter-kafka-test'
	testRuntimeOnly 'org.junit.platform:junit-platform-launcher'
}
