spring.application.name=producer

spring.kafka.bootstrap-servers=localhost:29092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

grid.producer.topic=electricity-readings
grid.producer.topic-partitions=12
grid.producer.district-count=23
grid.producer.meters-per-district=100
grid.producer.scheduler-pool-size=16
grid.producer.interval=5s
